<?php
?>
<table class="table table-bordered table-striped table-condensed">
<tr>
	<?php foreach($this->headers as $header): ?>
		<th><?= $header->getName(); ?></th>
	<?php endforeach; ?>
</tr>

	<? foreach($this->tableData as $row): ?>
	<tr <?//= $row->getRowStyle() ?>>
		<?php foreach($row as $col): ?>
			<td <?//= $col->getCellStyle() ?>> <?= $col ?> </td>
		<?php endforeach; ?>
	</tr>
	<?php endforeach; ?>

</table>
